/*
    NexOS Kernel Version v1.01.04
    Copyright (c) 2022 brodie

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */

#include <stdio.h>
#include <string.h>

#include "HardwareProfile.h"

#include "../NexOS/Kernel/Kernel.h"
#include "../NexOS/Kernel/Memory.h"
#include "../NexOS/Kernel/Task.h"
#include "../NexOS/Event/Event.h"
#include "../NexOS/Message Queue/MessageQueue.h"

#pragma config UPLLEN   = ON        	// USB PLL Enabled
#pragma config FPLLMUL  = MUL_20        // PLL Multiplier
#pragma config UPLLIDIV = DIV_2         // USB PLL Input Divider
#pragma config FPLLIDIV = DIV_2         // PLL Input Divider
#pragma config FPLLODIV = DIV_1         // PLL Output Divider
#pragma config FPBDIV   = DIV_1         // Peripheral Clock divisor
#pragma config FWDTEN   = OFF           // Watchdog Timer
#pragma config WDTPS    = PS1           // Watchdog Timer Postscale
#pragma config FCKSM    = CSDCMD        // Clock Switching & Fail Safe Clock Monitor
#pragma config OSCIOFNC = OFF           // CLKO Enable
#pragma config POSCMOD  = HS            // Primary Oscillator
#pragma config IESO     = ON            // Internal/External Switch-over
#pragma config FSOSCEN  = ON           	// Secondary Oscillator Enable (KLO was off)
#pragma config FNOSC    = PRIPLL        // Oscillator Selection
#pragma config CP       = OFF          	// Code Protect
#pragma config BWP      = OFF	        // Boot Flash Write Protect
#pragma config PWP      = OFF       	// Program Flash Write Protect
#pragma config ICESEL   = ICS_PGx2      // ICE/ICD Comm Channel Select
#pragma config DEBUG    = OFF            // Background Debugger Enable
#pragma config FVBUSONIO = OFF
#pragma config FCANIO 	= OFF			// OFF Enables Alternate CAN I/O

/*
 *  Example Code Goals:
 *      1. Generate some exceptions to showcase the exception handling (exceptions generated in MemoryAccessViolationTaskCode() method and DivideByZeroTaskCode() method).
 *      2. Show handling an exception and then outputting a message about it (found in GeneralExceptionHandlerUserCallback() method).
 *      3. Print out data generated by the GeneralExceptionHandlerUserCallback() to show the exceptions (found in EventSupervisorTaskCode() method).
 *      4. Show how to use the MESSAGE_QUEUE.
 * 
 *  Notes:
 *      The DivideByZeroTask is restarted upon the exception being generated and the MemoryAccessViolationTask is deleted upon generating an exception.
 *      It takes some time for the Maintenance Task to run for the deletion and restart to happen so let the program run a bit.
 * 
 *      This demo code is designed to work with the MPLAB X IDE Simulator.
 */

// This MESSAGE_QUEUE is used to communicate the messages from the GeneralExceptionHandlerUserCallback()
// to the Event Supervisor Task.  The Event Supervisor Task then prints out the messages.
MESSAGE_QUEUE gExceptionMessageQueue;

// We will use this pointer to see if it was the TASK which caused the current exception.
// Then for the sake of example, we will return TRUE in the GeneralExceptionHandlerUserCallback().
// Returning TRUE in GeneralExceptionHandlerUserCallback() will cause the current TASK to be 
// restarted and not deleted.
TASK *gDivideByZeroTask;

#if (USING_OS_GENERAL_EXCEPTION_HANDLER == 1)
    /*
     * This is called by the OS when an OS_EXCEPTION occurs.  It is optional and if used must be implemented by the user.
     */
    BOOL GeneralExceptionHandlerUserCallback(TASK *CurrentTask, OS_EXCEPTION_CODE ExceptionCode, UINT32 ExceptionAddress, BOOL UserCodeCurrentlyExecuting)
    {
        BYTE TempBuffer[128];
        BYTE *Data;
        
        // We should only do this if we know user code was running at the time of the exception.
        // Otherwise we don't know if the OS was in the heap when then exception occurred or anywhere else we may call in the OS.
        if(UserCodeCurrentlyExecuting == TRUE)
        {
            // build up the message to display
            sprintf((char*)TempBuffer, "%s @ Address 0x%08X by %s", ExceptionToString(ExceptionCode), (unsigned int)ExceptionAddress, CurrentTask->TaskName);

            // now get some space from the OS heap to store our message in
            // we add 1 for the NULL termination.
            Data = OS_AllocateMemory(strlen((char*)TempBuffer) + 1);

            // did we get the space
            if(Data == (BYTE*)NULL)
                while(1);

            // copy the data over to the newly allocated space
            strcpy((char*)Data, (const char*)TempBuffer);

            // Now add the message to the MESSAGE_QUEUE.
            // Calling this method technically should not be done from a callback since it can swap
            // out the currently executing TASK.  In this example it is OK (because in this scenario
            // a TASK will not get swapped in), but for field deployed code this is a big no no since 
            // we cannot guarantee that we won't get swapped out!
            if(MessageQueueAddFromISR(&gExceptionMessageQueue, Data) != OS_SUCCESS)
                while(1);
        }
        
        // We want to return FALSE from this method so the TASK is not restarted should that feature be enabled.
        // The currently executing TASK will be queued up for deletion after this method is called.
        return (BOOL)(CurrentTask == gDivideByZeroTask);
    }
#endif // end of #if (USING_OS_GENERAL_EXCEPTION_HANDLER == 1)
    
/*
 * This is the TASK code which will cause an address store exception.
 */
UINT32 MemoryAccessViolationTaskCode(void *Args)
{
    // lets do another exception
    UINT32 *AddressStoreException = (UINT32*)0xFFFFFFFF;

    *AddressStoreException = 0;
    
    while(1)
    {
        // we will never get due to the address store exception
    }
}

/*
 * This is the TASK code which will make a divide by zero error.
 */
UINT32 DivideByZeroTaskCode(void *Args)
{
    UINT32 Count = 0;
    
    // Cause a trap error 
    Args = (void*)(0xDEADBEEF / Count);
    
    while(1)
    {
        // We will never get here due to the divide by zero error
    }
}

/*
 * This TASK waits on the CPU_EXCEPTION_RAISED_EVENT to execute.  If an event of that
 * type occurs this TASK will print out information relevant to the exception.  The data
 * which is relevant to the exception is put into the gExceptionMessageQueue from the
 * method GeneralExceptionHandlerUserCallback().  This is a little dicey due to the fact
 * that an exception could technically happen anywhere in code.  As long as it doesn't happen
 * while manipulating the gExceptionMessageQueue or in the EventSupervisorTaskCode, we're good!
 * (which in the case of this example we're good, but perhaps not in your field deployed code!)
 */
UINT32 EventSupervisorTaskCode(void *Args)
{
    BYTE *Data;
    OS_RESULT Result;
    
    // Create our MESSAGE_QUEUE which will hold the strings to display
    if(CreateMessageQueue(&gExceptionMessageQueue, ReleaseMemory) == (MESSAGE_QUEUE*)NULL)
        while(1);
            
    while(1)
    {
        // Now wait for the CPU_EXCEPTION_RAISED_EVENT to happen
        Result = WaitOnEvent(CPU_EXCEPTION_RAISED_EVENT, 100);
        
        // now based off of Result, print out the information
        switch(Result)
        {
            case OS_SUCCESS:
            {
                // we shouldn't assume 1 event = 1 message (for this example it is, but always be aware), so keep displaying until they are all gone
                while(MessageQueueIsEmpty(&gExceptionMessageQueue) == FALSE)
                {
                    // read the next message out of the MESSAGE_QUEUE
                    if(MessageQueueRemove(&gExceptionMessageQueue, (void**)&Data) == OS_SUCCESS)
                    {
                        // print the data we read from the MESSAGE_QUEUE
                        printf("%s\n", Data);

                        // now free from the OS Heap the data that was allocated to make the message
                        if(MessageQueueFreeData(&gExceptionMessageQueue, (void*)Data) != OS_SUCCESS)
                            while(1);
                    }
                }
                
                break;
            }
            
            case OS_TASK_TIMEOUT:
            {
                // print out an error message about the timeout
                printf("%s: WaitOnEvent() timed out.  Trying again!\n", GetTaskName((TASK*)NULL));
                    
                break;
            }
            
            default:
            {
                // we should never get here
                while(1);
            }
        }
    }
}

int main(int argc, char** argv)
{
	#ifdef SIMULATION
        __XC_UART = 1;
	#endif // end of #if SIMULATION

    #ifndef SIMULATION		
        while(OSCCONbits.SLOCK != 1);
    #endif // end of #ifndef SIMULATION		

	mJTAGPortEnable(DEBUG_JTAGPORT_OFF);
    
    SetSystemClocks(GetSystemClock());
    
    // InitOS() must be called BEFORE ANY OTHER OS CALL!!!!
    if(InitOS() != OS_SUCCESS)
        while(1);
        
    #ifdef SIMULATION
    {
        BYTE KernelVersionString[16];
            
        printf("NexOS v%s\n\n", KernelVersionToString(KernelVersionString));
    }
	#endif // end of #if SIMULATION

    // Create a TASK which will cause the divide by zero error
    if((gDivideByZeroTask = CreateTask(DivideByZeroTaskCode, 1000, 1, (void*)0, TRUE, (BYTE*)"DIVIDE BY ZERO", (TASK*)NULL)) == (TASK*)NULL)
        while(1);
    
    // Create a simple TASK which will generate a memory access violation error
    if((CreateTask(MemoryAccessViolationTaskCode, 1000, 2, (void*)0, FALSE, (BYTE*)"ADDRESS EXCEPTION", (TASK*)NULL)) == (TASK*)NULL)
        while(1);
    
    // This TASK waits on an OS_EXCEPTION to occur and then prints out the OS_EXCEPTION data.
    if(CreateTask(EventSupervisorTaskCode, 200, 3, (void*)2, FALSE, (BYTE*)"EVENT MONITOR", (TASK*)NULL) == (TASK*)NULL)
        while(1);
    
    // This starts the OS Scheduler and will begin executing the TASK with the highest priority.
    StartOSScheduler();
    
    // We should never get here!
	return (EXIT_SUCCESS);
}
